version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      open-pull-requests-limit: 30
      target-branch: "main"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      open-pull-requests-limit: 30
      target-branch: "main"
