name: 🚀 CD

on:
    push:
        branches: [main]

jobs:
    CI:
      uses: thejaviertc/portfolio-javiertc/.github/workflows/ci.yml@main
    CD:
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v3

            - name: 🚀 Deploy Project
              uses: JamesIves/github-pages-deploy-action@v4.4.1
              with:
                  branch: gh-pages
                  folder: build
